# SharePoint Extract Pipeline
# runs on on-premises build agent and executes the shaarepoint extractor program
# to extract all sharepoint rules data & history into a data.json file.
# https://aka.ms/yaml

# schedules:
# - cron: 0 1 * * * # run at 1 am daily
#   displayName: nightly cron trigger 
#   # always run - the content source we're extracting isn't in this repo
#   always: boolean 

stages: 
- stage: extract
  displayName: "Extract From SharePoint"
  pool: 
    name: On-Premise
    demands: 
    - Agent.Name -equals $(buildAgentName)


  jobs: 
  - job: build
    steps:
    - task: MSBuild@1
      inputs:
        solution: SSW.Rules.SharePointExtractor\SSW.Rules.SharePointExtractor.sln


  - job: hello_world
    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'
